services:
  app:
    build:
      context: .
      target: prod
    env_file: .env
    volumes:
      - storage:/var/www/html/storage/app/public
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_net

  worker:
    build:
      context: .
      target: prod
    env_file: .env
    command: ["php", "artisan", "queue:work", "--sleep=3", "--tries=3", "--max-time=3600"]
    user: www-data
    volumes:
      - storage:/var/www/html/storage/app/public
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_net

  scheduler:
    build:
      context: .
      target: prod
    env_file: .env
    command: ["php", "artisan", "schedule:work"]
    user: www-data
    volumes:
      - storage:/var/www/html/storage/app/public
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel_net

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "8084:80"
    volumes:
      - storage:/var/www/html/public/storage
    depends_on:
      - app
    networks:
      - laravel_net

  db:
    image: mariadb:11.4
    restart: always
    env_file: .env
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - laravel_net
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  laravel_net:

volumes:
  storage:
