import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await (await b.newContext({ viewport:{width:1200,height:900} })).newPage();
await p.goto('http://localhost:8084/memes',{waitUntil:'networkidle'});
await p.evaluate(()=>localStorage.removeItem('memes-nsfw-ok'));
await p.reload({waitUntil:'networkidle'});
await p.waitForTimeout(500);
await p.screenshot({path:'nsfw-gate-clean.png'});
const z = await p.evaluate(()=>{const h=[...document.querySelectorAll('h2')].find(e=>e.textContent.includes('Content warning'));const g=h.closest('.fixed');const cs=getComputedStyle(g);return cs.backgroundColor+' | z='+cs.zIndex+' | pos='+cs.position;});
console.log('overlay:', z);
await b.close();
