import { chromium } from 'playwright';
const b = await chromium.launch();
const p = await (await b.newContext({ viewport:{width:1200,height:1000} })).newPage();
await p.goto('http://localhost:8084/memes',{waitUntil:'networkidle'});
await p.evaluate(()=>localStorage.setItem('memes-nsfw-ok','1'));
await p.reload({waitUntil:'networkidle'});
await p.waitForTimeout(700);
const blurs = await p.evaluate(()=>[...document.querySelectorAll('div')].filter(d=>d.className.includes('grid-cols')&&getComputedStyle(d).filter!=='none').length);
console.log('NSFW grids with active blur filter (expect >=2):', blurs);
await b.close();
